name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thanhdatnguyen1809/pbl6-app:latest
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}"
            "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}"
            "APP_PORT=${{ secrets.APP_PORT }}"
            "REGISTRY=${{ secrets.REGISTRY }}"
            "CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}"
            "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}"
            "SMTP_PASS=${{ secrets.SMTP_PASS }}"
            "SMTP_HOST=${{ secrets.SMTP_HOST }}"
            "SMTP_PORT=${{ secrets.SMTP_PORT }}"
            "SMTP_USER=${{ secrets.SMTP_USER }}"
